# Generated by Django 3.2.8 on 2021-10-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20211009_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='set',
        ),
        migrations.AddField(
            model_name='set',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.log'),
        ),
    ]
