# Generated by Django 3.2.8 on 2021-10-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='unit',
            field=models.CharField(choices=[('lb', 'pounds'), ('kg', 'kilograms')], default='lb', max_length=3),
        ),
    ]
