# Generated by Django 3.2.8 on 2021-10-13 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_alter_exercise_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('wl', 'Weight-Loss'), ('bb', 'Bodybuilding')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('exercises', models.ManyToManyField(blank=True, null=True, to='logger.Exercise')),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
