# Generated by Django 3.2.8 on 2021-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='category',
            field=models.CharField(choices=[('user', 'Custom'), ('server', 'Pre-made')], default='user', max_length=7),
        ),
    ]
